# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# /Users/runner/work/1/s/recipes/cutadapt, last modified Wed Apr 13 22:43:12 2022
# ------------------------------------------------

package:
  name: cutadapt
  version: '4.0'
source:
  sha256: 49c13c9f143c4a7b9bebc72b52f686e8ade30908a1d5a6725882d35c11dafa75
  url: https://files.pythonhosted.org/packages/c2/6e/f9d9671f2e5ee8683d6fc709eaf2184b05d8adc4861b41ac87133a5c23d2/cutadapt-4.0.tar.gz
build:
  number: '0'
  script: /usr/local/miniconda/envs/bioconda/conda-bld/cutadapt_1649890444450/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . --no-deps -vv
  string: py38h431a6f7_0
requirements:
  build:
    - ca-certificates 2021.10.8 h033912b_0
    - cctools_osx-64 973.0.1 h2b735b3_10
    - clang 12.0.1 h694c41f_4
    - clang-12 12.0.1 default_he082bbe_4
    - clang_osx-64 12.0.1 h633439f_8
    - clangxx 12.0.1 default_he082bbe_4
    - compiler-rt 12.0.1 he01351e_0
    - compiler-rt_osx-64 12.0.1 hd3f61c9_0
    - ld64_osx-64 609 hc6b1d1e_10
    - libclang-cpp12 12.0.1 default_he082bbe_4
    - libcxx 13.0.1 hc203e6f_0
    - libllvm12 12.0.1 hd011deb_2
    - libllvm13 13.0.1 h64f94b2_2
    - libzlib 1.2.11 h6c3fc93_1014
    - llvm-tools 12.0.1 hd011deb_2
    - openssl 3.0.2 h6c3fc93_1
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - zlib 1.2.11 h6c3fc93_1014
  host:
    - bzip2 1.0.8 h0d85af4_4
    - ca-certificates 2021.10.8 h033912b_0
    - cython 0.29.28 py38h038c8f4_2
    - libcxx 13.0.1 hc203e6f_0
    - libffi 3.4.2 h0d85af4_5
    - libzlib 1.2.11 h6c3fc93_1014
    - ncurses 6.3 h96cf925_1
    - openssl 3.0.2 h6c3fc93_1
    - packaging 21.3 pyhd8ed1ab_0
    - pip 22.0.4 pyhd8ed1ab_0
    - pyparsing 3.0.8 pyhd8ed1ab_0
    - python 3.8.13 h66c20e1_0_cpython
    - python_abi 3.8 2_cp38
    - readline 8.1 h05e3726_0
    - setuptools 62.1.0 py38h50d1736_0
    - setuptools-scm 6.4.2 pyhd8ed1ab_0
    - sqlite 3.38.2 hb516253_0
    - tk 8.6.12 h5dbffcc_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 haf1e3a3_1
    - zlib 1.2.11 h6c3fc93_1014
  run:
    - dnaio >=0.7.0
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - xopen >=1.2.0
test:
  commands:
    - cutadapt --version
  imports:
    - cutadapt
about:
  home: https://cutadapt.readthedocs.io/
  license: MIT
  summary: Trim adapters from high-throughput sequencing reads
extra:
  copy_test_source_files: true
  final: true
  identifiers:
    - biotools:cutadapt
    - doi:10.14806/ej.17.1.200
  recipe-maintainers:
    - marcelm
